# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: envanter_pg
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: envanter_db
    ports:
      - 15432:5432/tcp
