apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.app.name }}-svc
  annotations:
    {{- range $key, $value := .Values.app.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  namespace: {{ .Values.namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Values.env }}-{{ .Values.app.name }}
    env: {{ .Values.env }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.targetPort }}
      name: {{ .Values.app.name }}-port
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.app.targetPort }}
      name: {{ .Values.app.name }}-https-port
{{- if .Values.app.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.app.loadBalancerSourceRanges | indent 4 }}
{{- end }}
